-- [Service Name and version]
-- @Patriots8800
-- Documentation https://example.com

--!strict

----------------------------------------------------------------------------------------------

-- 							[[ Dependencies ]]



----------------------------------------------------------------------------------------------


-- 							[[ Types ]]




----------------------------------------------------------------------------------------------

-- 							[[ Service Header ]]

local SERVICE_NAME = ""


----------------------------------------------------------------------------------------------

-- 							[[ Private functions (helpers) ]]


----------------------------------------------------------------------------------------------
--					 		[[ MetaData (MetaTable) ]]




----------------------------------------------------------------------------------------------
--					 		[[ Public service (constructor) ]]



----------------------------------------------------------------------------------------------

-- Tags: https://eryn.io/moonwave/docs/TagList/

--[=[ 
    @class TEMPLATECLASS
    A class template
]=]

--[=[
    @within TEMPLATECLASS
    @type TEMPLATETYPE Test

    Template type
]=]

--[=[
    @within TEMPLATECLASS
    @interface TEMPLATEINTERFACE

    .T1 TEMPLATETYPE
    .T2 TEMPLATETYPE
    .T3 TEMPLATETYPE

    Template type
]=]

--[=[
    @within TEMPLATECLASS
    @function TEMPLATEFUNCTION

    @param T1 TEMPLATETYPE
    @return TEMPLATEINTERFACE

    Template type

]=]

--[=[
    @within TEMPLATECLASS
    @method TEMPLATEMETHOD

    @param T1 TEMPLATETYPE
    @return TEMPLATEINTERFACE

    Template type

    :::tip
        Tip Container
    :::
    :::info
        info Container
    :::
    :::caution
        caution Container
    :::
    :::danger
        danger Container
    :::

    | Head1 | Head2 | Head3 |
    |-------|-------|-------|
    | Prop1 | Prop2 | Prop3 |
]=]


--[=[
    @within TEMPLATECLASS
    
    @prop TEMPLATEPROPERTY1 boolean

]=]